In [1]:
import numpy as np 

In [2]:
myarray = [0.11,2.55,4.88,6.34]

In [3]:
myarray

[0.11, 2.55, 4.88, 6.34]

In [4]:
myarray2 = np.ceil(myarray)

In [5]:
myarray2


array([1., 3., 5., 7.])

In [6]:
myarray3 = [100.2,32.0095,54.18,777.34]

In [7]:
myarray3

[100.2, 32.0095, 54.18, 777.34]

In [8]:
myarray4 = np.ceil(myarray3)

In [9]:
myarray4

array([101.,  33.,  55., 778.])

In [10]:
myarray5 = [12.6,51.52,41.99999,10.88888]

In [11]:
myarray6 = np.fix(myarray5)

In [12]:
myarray6

array([12., 51., 41., 10.])

In [13]:
myarray7 = np.floor(myarray5)

In [14]:
myarray7

array([12., 51., 41., 10.])

In [15]:
myarray8 = np.rint(myarray5)

In [16]:
myarray5

[12.6, 51.52, 41.99999, 10.88888]